name: Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run Nushell Tests
    strategy:
      matrix:
        arch: ["", "-intel"]

        # Ref: https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md
        # Ref: https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md
        # Ref: https://github.com/actions/runner-images/blob/main/images/macos/macos-26-Readme.md
        # Ref: https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md
        #
        os_bundle:
          - os: macos-26
            xcode: 26.3
          - os: macos-15
            xcode: 26.3
          - os: macos-15
            xcode: 16.3

    runs-on: "${{ matrix.os_bundle.os }}${{ matrix.arch }}"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Nushell
        uses: hustcer/setup-nu@v3
        with:
          version: "0.114.0"

      - name: Xcode Versions
        run: ls -la /Applications/Xcode*

      - name: Xcode Select
        run: "sudo xcode-select -s /Applications/Xcode_${{ matrix.os_bundle.xcode }}.app"

      - name: Xcode Select
        run: xcode-select -p

      - name: Checkout vendored dependencies
        run: |
          git clone https://github.com/vyadh/nutest.git vendor/nutest
          git -C vendor/nutest checkout v1.2.0

      - name: Build Low-Latency Swift Broadcasting Engine
        run: |
          cd surface/broadcast
          xcrun swift build -c release

      - name: Run Tests
        shell: nu {0}
        run: |
          scripts/run_tests.nu --fail
